config/routes.rb
Rails.application.routes.draw do
  #get 'transactions/create', to: "transactions#create"
  #get 'transactions/update', to: "transactions#update"
  resources :sales
    #patch "sales/concrete", to: "sales#concrete"

  resources :inventory_items
  resources :employees
  resources :shops
  resources :product_statuses
  resources :products
  resources :product_types
  # servidores:
  # rails server
  # ruby .\bin\webpack-dev-server
  devise_for :users

  post "payment_details/create", to: "payment_details#create"

  ##Revenue
  get "revenue/", to: "revenue#index"

  ##Home
  get 'home/index', to: "home#index"
  root to: "home#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
## TODO: Crear Modelo para dar permisos y su respectivo controlador y vistas.

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :users
  belongs_to :shop
  has_many :inventory_items
  has_many :sales
  has_many :sale_sessions
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:name, :last_name_1, :last_name_2, :rfc, :address, :phone_home, :phone_mobile, :charge, :shop_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :last_name_1 %>
    <%= form.text_field :last_name_1 %>
  </div>

  <div class="field">
    <%= form.label :last_name_2 %>
    <%= form.text_field :last_name_2 %>
  </div>

  <div class="field">
    <%= form.label :rfc %>
    <%= form.text_field :rfc %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :phone_home %>
    <%= form.number_field :phone_home %>
  </div>

  <div class="field">
    <%= form.label :phone_mobile %>
    <%= form.number_field :phone_mobile %>
  </div>

  <div class="field">
    <%= form.label :charge %>
    <%= form.text_field :charge %>
  </div>

  <% options = [['Seleccione',0]] %>
  <% Shop.all.each do |shop| %>
    <% options.push([shop.name,shop.id]) %>
  <% end %>

  <div class="field">
    <%= form.label :shop_id %>
    <%= form.select( :shop_id, options_for_select(options, @employee.shop_id) ) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Last name 1</th>
      <th>Last name 2</th>
      <th>Rfc</th>
      <th>Address</th>
      <th>Phone home</th>
      <th>Phone mobile</th>
      <th>Shop</th>
      <th>Charge</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.last_name_1 %></td>
        <td><%= employee.last_name_2 %></td>
        <td><%= employee.rfc %></td>
        <td><%= employee.address %></td>
        <td><%= employee.phone_home %></td>
        <td><%= employee.phone_mobile %></td>
        <td><%= employee.shop.name %></td>
        <td><%= employee.charge %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Last name 1:</strong>
  <%= @employee.last_name_1 %>
</p>

<p>
  <strong>Last name 2:</strong>
  <%= @employee.last_name_2 %>
</p>

<p>
  <strong>Rfc:</strong>
  <%= @employee.rfc %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee.address %>
</p>

<p>
  <strong>Phone home:</strong>
  <%= @employee.phone_home %>
</p>

<p>
  <strong>Phone mobile:</strong>
  <%= @employee.phone_mobile %>
</p>

<p>
  <strong>Charge:</strong>
  <%= @employee.shop.name %>
</p>

<p>
  <strong>Charge:</strong>
  <%= @employee.charge %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>