config/routes.rb
Rails.application.routes.draw do
  #get 'transactions/create', to: "transactions#create"
  #get 'transactions/update', to: "transactions#update"
  resources :sales
    #patch "sales/concrete", to: "sales#concrete"

  resources :inventory_items
  resources :employees
  resources :shops
  resources :product_statuses
  resources :products
  resources :product_types
  # servidores:
  # rails server
  # ruby .\bin\webpack-dev-server
  devise_for :users

  post "payment_details/create", to: "payment_details#create"

  ##Revenue
  get "revenue/", to: "revenue#index"

  ##Home
  get 'home/index', to: "home#index"
  root to: "home#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
## TODO: Crear Modelo para dar permisos y su respectivo controlador y vistas.

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :employees
  has_many :inventory_items
  has_many :sales
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:name, :pseudonym, :address, :city)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_with(model: shop, local: true) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
        <% shop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :pseudonym %>
    <%= form.text_field :pseudonym %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pseudonym</th>
      <th>Address</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.name %></td>
        <td><%= shop.pseudonym %></td>
        <td><%= shop.address %></td>
        <td><%= shop.city %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shop.name %>
</p>

<p>
  <strong>Pseudonym:</strong>
  <%= @shop.pseudonym %>
</p>

<p>
  <strong>Address:</strong>
  <%= @shop.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @shop.city %>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>